version: 2.1

executors:
  maven-executor:
    docker:
      - image: maven:3.8.3-jdk-11
    environment:
      MAVEN_OPTS: "-Dmaven.repo.local=$HOME/.m2/repository"

jobs:
  build-and-test:
    executor: maven-executor
    steps:
      - checkout

      - run:
          name: Build and Test
#          command: mvn clean verify
          command: mvn test

      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts

  upload-report:
    executor: maven-executor
    steps:
      - run:
          name: Upload Report
          command: |
            mkdir -p test-reports
            cp -R target/site/serenity test-reports/
            # Additional commands to upload the test report to a storage or reporting service

workflows:
  version: 2
  build-and-upload:
    jobs:
      - build-and-test
      - upload-report:
          requires:
            - build-and-test




