version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      # Set up your environment, install dependencies, etc.
      # ...

      - run:
          name: Build and test
          command: mvn clean test

  check_tests:
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      # Set up your environment, install dependencies, etc.
      # ...

      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Check test results
          command: |
            if [ -e "/tmp/workspace/target/surefire-reports/TEST-*.xml" ]; then
              echo "All tests passed!"
              exit 0
            else
              echo "Some tests failed or no test results found."
              exit 1
            fi

workflows:
  version: 2
  build_and_check:
    jobs:
      - build
      - check_tests:
          requires:
            - build
