version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - run:
          name: Build and Run Tests
          command: mvn clean verify

      - store_artifacts:
          path: target/site/serenity
          destination: serenity_reports

workflows:
  version: 2
  build:
    jobs:
      - build
